postgresql:
  initdbScripts:
    init.sql: |-
      CREATE USER ccd WITH PASSWORD 'ccd';
      CREATE DATABASE ccd_data_store WITH OWNER = ccd ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  nameOverride: postgres
  persistence:
    enabled: false

java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 4452
  applicationInsightsInstrumentKey: "fake-key"
  keyVaults:
    s2s:
      resourceGroup: rpe-service-auth-provider
      secrets:
        - microservicekey-ccd-data
  environment:
    ENABLE_DB_MIGRATE: true
    DATA_STORE_DB_HOST: ${SERVICE_NAME}-postgres
    DATA_STORE_DB_PORT: 5432
    DATA_STORE_DB_NAME: ccd_data_store
    DATA_STORE_DB_USERNAME: ccd
    DATA_STORE_DB_USE_SSL: false

    CCD_DM_DOMAIN: https?://dm-store.*

    IDAM_USER_URL: https://idam-api.aat.platform.hmcts.net

    CCD_DRAFT_TTL_DAYS: 180

    DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_ps,probate_backend,divorce_ccd_submission,sscs,sscs_bulkscan,cmc,cmc_claim_store,jui_webapp,pui_webapp,bulk_scan_orchestrator,fpl_case_service,iac,finrem_ccd_data_migrator

    DEFINITION_CACHE_TTL_SEC: 259200
    DEFINITION_CACHE_MAX_SIZE: 5000
    DEFINITION_CACHE_EVICTION_POLICY: NONE

    ELASTIC_SEARCH_ENABLED: false
    ELASTIC_SEARCH_HOSTS: ''
    ELASTIC_SEARCH_DATA_NODES_HOSTS: ''
    ELASTIC_SEARCH_PASSWORD: ''
    ELASTIC_SEARCH_BLACKLIST: query_string
    ELASTIC_SEARCH_CASE_INDEX_NAME_FORMAT: '%s_cases'
    ELASTIC_SEARCH_CASE_INDEX_TYPE: _doc

    IDAM_S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    DEFINITION_STORE_HOST: http://ccd-definition-store-api-aat.service.core-compute-aat.internal
    USER_PROFILE_HOST: http://ccd-user-profile-api-aat.service.core-compute-aat.internal
    CCD_DM_DOMAIN: ^https?://(?:api-gateway\\.preprod\\.dm\\.reform\\.hmcts\\.net|dm-store-aat\\.service\\.core-compute-aat\\.internal(?::\\d+)?)
    IDAM_URL_URL: https://idam-api.aat.platform.hmcts.net
    #    IDAM_USER_URL: https://preprod-idamapi.reform.hmcts.net:3511
    CCD_DRAFT_STORE_URL: http://draft-store-service-aat.service.core-compute-aat.internal
    CCD_DEFAULTPRINTURL: https://return-case-doc-ccd.nonprod.platform.hmcts.net/jurisdictions/:jid/case-types/:ctid/cases/:cid

tags:
  postgresql-pod: true
